sudo: required
services:
  - docker
before_install:
  - docker build -t raghav/react-test -f ./client/Dockerfile.dev ./client 

script:
 - docker run -e CI=true raghav/react-test npm test

afterafter_success:
  - docker build -t raghav/multi-client ./client
  - docker build -t raghav/multi-nginx ./nginx
  - docker build -t raghav/multi-worker ./worker
  - docker build -t raghav/multi-server ./server

# Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

# Take those images and push them to docker hub
  - docker push raghav/multi-client
  - docker push raghav/multi-nginx
  - docker push raghav/multi-worker
  - docker push raghav/multi-server

